### ISSUE TITLE
Change: GitHub Pagesへのデプロイ方法を新しいのにする。

### ISSUE THREAD

**Issue by tasuren** [nattyan-tv/dinosaur-homepage#5]
# 概要
GitHub Pagesに公式的にブランチを使わないやり方でデプロイをするための機能が最近実装された。
まだベータではあるが、こっちの方が効率が良い。
だから、これのやり方に移行をする方が好ましい。

**Comment by nattyan-tv** [comment]
レポジトリの設定変えて、`deploy`jobの`Deploy`stepを変えて、なんか色々追加して....(？)
```yaml
      - name: Deploy
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./output
```
(みたいな感じ...？)
(お任せします(以下省略))

参考: https://yoshinorin.net/articles/2022/11/10/deploy-ghpages-with-ghactions/
